version: '3.4'

services:
    mongodb:
        image: mongo

    mongodbtemplate.api:
        image: ${DOCKER_REGISTRY-}mongodbtemplateapi
        build:
            context: .
            dockerfile: MongoDBTemplate.API/Dockerfile