version: '3.4'

services:
    mongodb:
        container_name: mongodb
        restart: always
        volumes:
            - ${WEBAPP_STORAGE_HOME}/site:/data/db
            #- ./data:/data/db
        ports:
            - "27017:27017"

    mongodbtemplate.api:
        container_name: mongodbtemplateapi
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "AppSettings:ConnectionString=mongodb://mongodb:27017"
        depends_on:
            - mongodb
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
        ports:
            - "9001:80"